### ISSUE TITLE
2 main issues with Poz Perceptions design

### ISSUE THREAD

**Issue by AditiBhandari** [Medill/TheFlux#6]
![screen shot 2015-05-22 at 17 39 00](https://cloud.githubusercontent.com/assets/9308945/7780812/8a837050-00a9-11e5-9e50-8916a794d064.png)
@zachwise @richafur @emilywithrow: The two biggest issues we were facing with our design were the navigation system (though I think Zach has fixed that) and how to seamlessly integrate the medical jargon with the narratives without disrupting the flow of the story. We decided that at the beginning of each story, we'd have a small glossary of the few terms mentioned in that story with the definitions highlighted using the <mark> tags, and within the story they'd be highlighted with a small dropdown option (like in the screenshot) to see the definition once again if the reader wants to remind themself. The latest attempt was semi successful, any ideas what else I should try?

**Comment by emilywithrow** [comment]
Zach and I talked awhile about this--it's important that these don't read so big to distract from the story--these definitions are really supplemental information and therefore (a) shouldn't disrupt the flow of your story, and (b) shouldn't be prominently displayed so that it becomes part of the scan-read. So: we wanted to advise you to come up with a "hidden" solution for medium and large screens where that scroll-level read is important, and then find an integrated approach for mobile. Does that make sense?
